services:
  backend:
    build: ./backend
    ports:
      - "5001:5001"
    volumes:
      - ./backend/uploads:/app/uploads
    environment:
      - NODE_ENV=production
    networks:
      - somdosilencio
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.nginx
    ports:
      - "4200:80"
    depends_on:
      - backend
    networks:
      - somdosilencio

networks:
  somdosilencio:
    driver: bridge
